# fly.toml app configuration file generated for concesionario-backend on 2023-08-22T23:48:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "concesionario-backend"
primary_region = "bog"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
